on:
  push:
    branches:
      - main
      - staging
      - test/*

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Create a release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
          # this is a built-in strategy in release-please, see "Action Inputs"
          # for more options
          release-type: node
          target-branch: ${{ github.ref_name }}

      - name: Checkout repository
        uses: actions/checkout@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          fetch-depth: 0
          persist-credentials: false

      # - name: Add major and minor versions as tags
      #   if: ${{ steps.release.outputs.release_created }}
      #   run: |
      #     echo "Creating additional tags for: ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}.${{ steps.release.outputs.patch }}"
      #     git config --global user.email "osman@gorm.us"
      #     git config --global user.name "Release Please"
      #     git tag -d v${{ steps.release.outputs.major }} || true
      #     git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
      #     git push origin :v${{ steps.release.outputs.major }} || true
      #     git push origin :v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
      #     git tag -a v${{ steps.release.outputs.major }} -m "Release v${{ steps.release.outputs.major }}"
      #     git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
      #     git push origin v${{ steps.release.outputs.major }}
      #     git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: "lts/*"
          registry-url: https://npm.pkg.github.com/
          scope: "@${{ github.repository_owner }}"

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: npm clean-install

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: npm audit signatures

      - name: Publish a package
        if: ${{ steps.release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
        run: npm publish --access=restricted
